services:
  - type: web
    name: vocabbuilder
    env: node
    buildCommand: npm install
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROUP_ID
        value: "120363377431957386@g.us"